

services:
  app:
    build: .
    container_name: rust_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local